#include "words_database.hpp"
#include <iostream>

// Current word count: 10
const WordData words[100] = {
    // Pronouns
    { "나", "I (informal)" },
    { "저", "I (polite)" },
    { "너", "You (informal)" },
    { "당신", "You (formal)" },
    { "우리", "We, our" },
    { "그", "He, that person" },
    { "그녀", "She" },
    { "이것", "This thing" },
    { "그것", "That thing" },
    { "누구", "Who" },

    // Nouns
    { "사람", "Person" },
    { "친구", "Friend" },
    { "가족", "Family" },
    { "엄마", "Mom" },
    { "아빠", "Dad" },
    { "아이", "Child" },
    { "집", "House, Home" },
    { "학교", "School" },
    { "회사", "Company" },
    { "학생", "Student" },
    { "선생님", "Teacher" },
    { "책", "Book" },
    { "물", "Water" },
    { "음식", "Food" },
    { "밥", "Meal, Rice (cooked)" },
    { "커피", "Coffee" },
    { "차", "Tea, Car" },
    { "시간", "Time" },
    { "날", "Day" },
    { "오늘", "Today" },
    { "내일", "Tomorrow" },
    { "어제", "Yesterday" },
    { "돈", "Money" },
    { "이름", "Name" },
    { "한국", "korea" },
    { "한국어", "Korean (language)" },
    { "영어", "English" },
    { "길", "Road, Street" },
    { "문", "Door" },
    { "방", "Room" },

    // Verbs
    { "가다", "To go" },
    { "오다", "To come" },
    { "보다", "To see/watch" },
    { "먹다", "To eat" },
    { "마시다", "To drink" },
    { "하다", "To do" },
    { "있다", "To exist/have" },
    { "없다", "To not exist/have" },
    { "자다", "To sleep" },
    { "일어나다", "To wake up" },
    { "공부하다", "To study" },
    { "배우다", "To learn" },
    { "가르치다", "To teach" },
    { "듣다", "To listen" },
    { "말하다", "To speak" },
    { "읽다", "To read" },
    { "쓰다", "To write" },
    { "사다", "To buy" },
    { "팔다", "To sell" },
    { "만나다", "To meet" },
    { "좋아하다", "To like" },
    { "알다", "To know" },
    { "모르다", "To not know" },
    { "만들다", "To make" },
    { "기다리다", "To wait" },
    { "그리다", "To draw" },
    { "살다", "To live." },
    { "주다", "To give." },

    // Adjectives
    { "좋다", "Good" },
    { "나쁘다", "Bad" },
    { "크다", "Big" },
    { "작다", "Small" },
    { "많다", "Many, much" },
    { "적다", "Few, little" },
    { "새롭다", "New" },
    { "오래되다", "Old (object)" },
    { "빠르다", "Fast" },
    { "느리다", "Slow" },
    { "쉽다", "Easy" },
    { "어렵다", "Difficult" },
    { "예쁘다", "Pretty" },
    { "행복하다", "Happy" },
    { "피곤하다", "Tired" },
    { "은은하다", "Subtle." },

    // Adverbs
    { "아주", "Very" },
    { "정말", "Really" },
    { "잘", "Well" },
    { "조금", "A little" },
    { "많이", "A lot" },
    { "빨리", "Quickly" },
    { "천천히", "Slowly" },
    { "항상", "Always" },
    { "자주", "Often" },
    { "지금", "Now" },

    // Ws and Hs
    { "언제", "When" },
    { "어디", "Where" },
    { "왜", "Why" },
    { "무엇", "What" },
    { "어떻게", "How" },
    { "어느", "Which" },
};

const int word_count = sizeof(words) / sizeof(WordData);
